import { Theme as NavigationTheme } from "@react-navigation/native";
import { Theme as PaperTheme } from "react-native-paper/lib/typescript/types";
import { DefaultTheme } from "react-native-paper";

/*
#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=5000u0kh+fE0UZGgbvpqg8KGO24


*** Primary color:

   shade 0 = #7D3737 = rgb(125, 55, 55) = rgba(125, 55, 55,1) = rgb0(0.49,0.216,0.216)
   shade 1 = #FFF8F8 = rgb(255,248,248) = rgba(255,248,248,1) = rgb0(1,0.973,0.973)
   shade 2 = #FA7C7C = rgb(250,124,124) = rgba(250,124,124,1) = rgb0(0.98,0.486,0.486)
   shade 3 = #460C0C = rgb( 70, 12, 12) = rgba( 70, 12, 12,1) = rgb0(0.275,0.047,0.047)
   shade 4 = #100000 = rgb( 16,  0,  0) = rgba( 16,  0,  0,1) = rgb0(0.063,0,0)

*** Secondary color (1):

   shade 0 = #7D5637 = rgb(125, 86, 55) = rgba(125, 86, 55,1) = rgb0(0.49,0.337,0.216)
   shade 1 = #FFFBF8 = rgb(255,251,248) = rgba(255,251,248,1) = rgb0(1,0.984,0.973)
   shade 2 = #FAB57C = rgb(250,181,124) = rgba(250,181,124,1) = rgb0(0.98,0.71,0.486)
   shade 3 = #46260C = rgb( 70, 38, 12) = rgba( 70, 38, 12,1) = rgb0(0.275,0.149,0.047)
   shade 4 = #100700 = rgb( 16,  7,  0) = rgba( 16,  7,  0,1) = rgb0(0.063,0.027,0)

*** Secondary color (2):

   shade 0 = #642C4C = rgb(100, 44, 76) = rgba(100, 44, 76,1) = rgb0(0.392,0.173,0.298)
   shade 1 = #FDF6FA = rgb(253,246,250) = rgba(253,246,250,1) = rgb0(0.992,0.965,0.98)
   shade 2 = #C9639D = rgb(201, 99,157) = rgba(201, 99,157,1) = rgb0(0.788,0.388,0.616)
   shade 3 = #380A24 = rgb( 56, 10, 36) = rgba( 56, 10, 36,1) = rgb0(0.22,0.039,0.141)
   shade 4 = #0D0007 = rgb( 13,  0,  7) = rgba( 13,  0,  7,1) = rgb0(0.051,0,0.027)


#####  Generated by Paletton.com (c) 2002-2014
*/
export const autumnColors = {
  primary: "#FFF8F8",
  accent: "#FA7C7C",
  background: "#1E0000",
  surface: "#230003",
  text: "#FFF8F8",
  disabled: "#AE3B46",
  placeholder: "#AE3B46",
  backdrop: "#230003",
  onSurface: "#E4C5AF",
  notification: "#FFB2B2",
  card: "#230003",
  border: "#FFB2B2",
};

/*

#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=53L0u0klelM4yXDeNLYtzbEL+1o


*** Primary color:

   shade 0 = #2F4474 = rgb( 47, 68,116) = rgba( 47, 68,116,1) = rgb0(0.184,0.267,0.455)
   shade 1 = #D7E0F6 = rgb(215,224,246) = rgba(215,224,246,1) = rgb0(0.843,0.878,0.965)
   shade 2 = #7E99D7 = rgb(126,153,215) = rgba(126,153,215,1) = rgb0(0.494,0.6,0.843)
   shade 3 = #0B1A3E = rgb( 11, 26, 62) = rgba( 11, 26, 62,1) = rgb0(0.043,0.102,0.243)
   shade 4 = #000207 = rgb(  0,  2,  7) = rgba(  0,  2,  7,1) = rgb0(0,0.008,0.027)

*** Secondary color (1):

   shade 0 = #423177 = rgb( 66, 49,119) = rgba( 66, 49,119,1) = rgb0(0.259,0.192,0.467)
   shade 1 = #DFD8F7 = rgb(223,216,247) = rgba(223,216,247,1) = rgb0(0.875,0.847,0.969)
   shade 2 = #9681DA = rgb(150,129,218) = rgba(150,129,218,1) = rgb0(0.588,0.506,0.855)
   shade 3 = #180C40 = rgb( 24, 12, 64) = rgba( 24, 12, 64,1) = rgb0(0.094,0.047,0.251)
   shade 4 = #020008 = rgb(  2,  0,  8) = rgba(  2,  0,  8,1) = rgb0(0.008,0,0.031)

*** Secondary color (2):

   shade 0 = #236868 = rgb( 35,104,104) = rgba( 35,104,104,1) = rgb0(0.137,0.408,0.408)
   shade 1 = #D2F4F4 = rgb(210,244,244) = rgba(210,244,244,1) = rgb0(0.824,0.957,0.957)
   shade 2 = #6FCFCF = rgb(111,207,207) = rgba(111,207,207,1) = rgb0(0.435,0.812,0.812)
   shade 3 = #043838 = rgb(  4, 56, 56) = rgba(  4, 56, 56,1) = rgb0(0.016,0.22,0.22)
   shade 4 = #000707 = rgb(  0,  7,  7) = rgba(  0,  7,  7,1) = rgb0(0,0.027,0.027)


#####  Generated by Paletton.com (c) 2002-2014
*/
export const winterColors = {
  primary: "#D7E0F6",
  accent: "#7E99D7",
  background: "#020816",
  surface: "#0B1A3E",
  text: "#D7E0F6",
  disabled: "#2F4474",
  placeholder: "#2F4474",
  backdrop: "#0B1A3E",
  onSurface: "#E4C5AF",
  notification: "#7E99D7",
  card: "#0B1A3E",
  border: "#7E99D7",
};

export type AppTheme = PaperTheme & NavigationTheme & { name: string };

export const themes: AppTheme[] = [
  {
    ...DefaultTheme,
    dark: true,
    name: "winter",
    colors: {
      ...DefaultTheme.colors,
      ...winterColors,
    },
  },
  {
    ...DefaultTheme,
    dark: true,
    name: "autumn",
    colors: {
      ...DefaultTheme.colors,
      ...autumnColors,
    },
  },
];
